apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: ui
  name: ui
spec:
  type: LoadBalancer
  selector:
    io.kompose.service: ui
  ports:
  - port: 80
    targetPort: 3000
status:
  loadBalancer: {}
