---
version: '3'

services:
    master:
        build:
            context: .
            dockerfile: ./master.Dockerfile
        environment: 
            HTTP_PORT: 9000
            REDIS_MASTER_NAME: mymaster
            RPC_PORT: 8080
            SENTINELS: distributed-evolution_sentinel_1:26379,distributed-evolution_sentinel_2:26379,distributed-evolution_sentinel_3:26379
            START_RANDOM_JOB: "true"
            WORKERS: 5
            WORKER_THREADS: 5
        ports:
            - 9000:9000
            - 8080
    worker:
        build:
            context: .
            dockerfile: ./worker.Dockerfile
        environment: 
            MASTER_URL: master:8080
            REDIS_MASTER_NAME: mymaster
            SENTINELS: distributed-evolution_sentinel_1:26379,distributed-evolution_sentinel_2:26379,distributed-evolution_sentinel_3:26379
            THREADS: 5
    ui:
        build: ui
        environment: 
            API_URL: http://localhost:9000/api
            CHANNEL_URL: ws://localhost:9000/api/subscribe
            NODE_ENV: development
            PORT: 3000
        ports:
            - 3000:3000
        restart: unless-stopped
        volumes:
            - ./ui/:/app
            - /app/node_modules/
            - /app/.next
    redis-master:
        image: redis:3
        ports:
            - 6379
    redis-slave:
        image: redis:3
        command: redis-server --slaveof redis-master 6379
        links:
            - redis-master
        ports:
            - 6379
    sentinel:
        build: sentinel/dev
        environment:
            - SENTINEL_DOWN_AFTER=5000
            - SENTINEL_FAILOVER=5000
        links:
            - redis-master
            - redis-slave
        ports:
            - 26379

networks:
    default:
        external:
            name: distributed-ga
