---
version: '3'

services:
    master:
        build:
            context: .
            dockerfile: ./master.Dockerfile
        environment: 
            DB_URL: db:6379
            HTTP_PORT: 9000
            WORKERS: 4
            WORKER_THREADS: 4
            RPC_PORT: 8080
        ports:
            - 9000:9000
            - 8080
    worker:
        build:
            context: .
            dockerfile: ./worker.Dockerfile
        environment: 
            DB_URL: db:6379
            MASTER_URL: master:8080
            THREADS: 4
    ui:
        build:
            context: .
            dockerfile: ./ui.Dockerfile
        environment: 
            API_URL: http://localhost:9000
            CHANNEL_URL: ws://localhost:9000/subscribe
            NODE_ENV: development
            PORT: 3000
        ports:
            - 3000:3000
        restart: unless-stopped
        volumes:
            - ./ui/:/app
            - /app/node_modules/
            - /app/.next
    db:
        image: redis
        ports:
            - 6379
        # volumes:
        #     - ./redis.conf:/usr/local/etc/redis/redis.conf
        # command: redis-server /usr/local/etc/redis/redis.conf

networks:
    default:
        external:
            name: distributed-ga
