---
version: '3'

services:
    master:
        build:
            context: .
            dockerfile: ./master.Dockerfile
        environment: 
            HTTP_PORT: 9000
            NUM_WORKERS: 16
            RPC_PORT: 8080
        ports:
            - 9000:9000
            - 8080
    worker:
        build:
            context: .
            dockerfile: ./worker.Dockerfile
        environment: 
            PORT: 8080
    ui:
        build:
            context: .
            dockerfile: ./ui.Dockerfile
        environment: 
            API_URL: localhost:9000
            NODE_ENV: development
            PORT: 3000
        ports:
            - 3000:3000
        restart: unless-stopped
        volumes:
            - ./ui/:/app
            - /app/node_modules/
            - /app/.next

networks:
    default:
        external:
            name: distributed-ga
