---
version: '3'

services:
    master:
        build:
            context: .
            dockerfile: ./master.Dockerfile
        command: go run .
        environment: 
            HTTP_PORT: 9000
            RPC_PORT: 8080
        ports:
            - 9000:9000
            - 8080
    worker:
        build:
            context: .
            dockerfile: ./worker.Dockerfile
        command: go run .
        environment: 
            PORT: 8080
    interface:
        build:
            context: .
            dockerfile: ./interface.Dockerfile
        command: npm run start:nodemon
        environment: 
            API_URL: localhost:9000
            NODE_ENV: development
            PORT: 3000
        ports:
            - 3000:3000
        restart: unless-stopped
        volumes:
            - ./interface/:/app
            - /app/node_modules/
            - /app/.next

networks:
    default:
        external:
            name: distributed-ga
