---
    version: '3'
    
    services:
        single-system:
            build:
                context: .
                dockerfile: single-system.Dockerfile
            environment: 
                HTTP_PORT: 9001
                START_RANDOM_JOB: "false"
            ports:
                - 9001:9001
        ui:
            build:
                context: ui
                dockerfile: dev.Dockerfile
            environment: 
                API_URL: http://localhost:9001/api
                CHANNEL_URL: ws://localhost:9001/api/subscribe
                NODE_ENV: development
                PORT: 3000
            ports:
                - 3000:3000
            restart: unless-stopped
            volumes:
                - ./ui/:/app
                - /app/node_modules/
                - /app/.next
    
    networks:
        default:
            external:
                name: distributed-ga
    