# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   creationTimestamp: null
#   labels:
#     app: ui
#   name: ui
# spec:
#   replicas: 1
#   selector:
#     matchLabels:
#       app: ui
#   strategy:
#     type: Recreate
#   template:
#     metadata:
#       creationTimestamp: null
#       labels:
#         app: ui
#     spec:
#       containers:
#       - name: ui
#         image: julesyoungberg/distributed-evolution-ui
#         imagePullPolicy: ""
#         ports:
#         - containerPort: 3000
#         env:
#         - name: API_URL
#           value: http://34.107.198.190/api
#         - name: CHANNEL_URL
#           value: ws://34.107.198.190/api/subscribe
#         - name: NODE_ENV
#           value: development
#         - name: PORT
#           value: "3000"
#         readinessProbe:
#           httpGet:
#             path: /
#             port: 3000
#         resources:
#           requests:
#             cpu: 0.02
#             memory: 10Mi
#           limits:
#             cpu: 0.04
#             memory: 20Mi
#       restartPolicy: Always
#       serviceAccountName: ""
# status: {}
