apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: worker
  name: worker
spec:
  replicas: 6
  selector:
    matchLabels:
      app: worker
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: worker
    spec:
      containers:
      - name: worker
        image: julesyoungberg/distributed-evolution-worker
        imagePullPolicy: ""
        env:
        - name: MASTER_URL
          value: master:8080
        - name: REDIS_MASTER_NAME
          value: mymaster
        - name: SENTINELS
          value: sentinel-master:26379
        - name: THREADS
          value: "6"
        resources:
          requests:
            cpu: 2.5
            memory: 100Mi
          limits:
            cpu: 3
            memory: 500Mi
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status: {}
