apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-kompose.yml
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: master
  name: master
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: master
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-kompose.yml
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.network/distributed-ga: "true"
        io.kompose.service: master
    spec:
      containers:
      - env:
        - name: HTTP_PORT
          value: "9000"
        - name: REDIS_MASTER_NAME
          value: mymaster
        - name: RPC_PORT
          value: "8080"
        - name: SENTINEL_ADDRESS
          value: sentinel:26379
        - name: WORKERS
          value: "5"
        - name: WORKER_THREADS
          value: "5"
        image: julesyoungberg/distributed-evolution-master
        imagePullPolicy: ""
        name: master
        ports:
        - containerPort: 9000
        - containerPort: 8080
        resources: {}
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status: {}
