apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: master
  name: master
spec:
  type: LoadBalancer
  selector:
    io.kompose.service: master
  ports:
  - name: http
    port: 80
    targetPort: 9000
  - name: rpc
    port: 8080
    targetPort: 8080
status:
  loadBalancer: {}
