apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: redis-slave
  name: redis-slave
spec:
  selector:
    io.kompose.service: redis-slave
  ports:
  - port: 6379
    targetPort: 6379
status:
  loadBalancer: {}
