apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: redis-slave
  name: redis-slave
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: redis-slave
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: redis-slave
    spec:
      containers:
      - name: redis-slave
        image: redis:3
        imagePullPolicy: ""
        args:
        - redis-server
        - --slaveof
        - redis-master
        - "6379"
        ports:
        - containerPort: 6379
        env:
        - name: GET_HOSTS_FROM
          value: dns
        resources: {}
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status: {}
