apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: sentinel
  name: sentinel
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: sentinel
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: sentinel
    spec:
      containers:
      - name: sentinel
        image: julesyoungberg/distributed-evolution-sentinel
        imagePullPolicy: ""
        ports:
        - containerPort: 26379
        env:
        - name: SENTINEL_DOWN_AFTER
          value: "5000"
        - name: SENTINEL_FAILOVER
          value: "5000"
        resources: {}
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status: {}
