apiVersion: apps/v1
kind: Deployment
metadata:
  name: sentinel-replica
  labels:
    app: sentinel-replica
spec:
  selector:
    matchLabels:
      app: sentinel-replica
  replicas: 2
  template:
    metadata:
      labels:
        app: sentinel-replica
    spec:
      containers:
      - name: replica
        image: julesyoungberg/distributed-evolution-sentinel-replica
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        env:
        - name: REDIS_MASTER_SERVICE_HOST
          value: sentinel-master
        - name: REDIS_MASTER_SERVICE_PORT
          value: "6379"
        - name: SENTINEL_ANNOUNCE_PORT
          value: "26379"
        - name: MY_POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        ports:
        - name: redis-sentinel
          containerPort: 26379
