apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: sentinel
  name: sentinel
spec:
  selector:
    io.kompose.service: sentinel
  ports:
  - port: 26379
    targetPort: 26379
status:
  loadBalancer: {}
