apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.service.type: LoadBalancer
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: ui
  name: ui
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: ui
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.service.type: LoadBalancer
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.service: ui
    spec:
      containers:
      - env:
        - name: API_URL
          value: http://distributed.ga/api
        - name: CHANNEL_URL
          value: ws://distributed.ga/api/subscribe
        - name: GET_HOSTS_FROM
          value: dns
        - name: NODE_ENV
          value: development
        - name: PORT
          value: "3000"
        image: julesyoungberg/distributed-evolution-ui
        imagePullPolicy: ""
        name: ui
        ports:
        - containerPort: 3000
        resources: {}
      restartPolicy: Always
      serviceAccountName: ""
status: {}
