apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: ui
  name: ui
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: ui
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: ui
    spec:
      containers:
      - name: ui
        image: julesyoungberg/distributed-evolution-ui
        imagePullPolicy: ""
        ports:
        - containerPort: 3000
        env:
        - name: API_URL
          value: http://distributed.ga/api
        - name: CHANNEL_URL
          value: ws://distributed.ga/api/subscribe
        - name: NODE_ENV
          value: development
        - name: PORT
          value: "3000"
        resources: {}
      restartPolicy: Always
      serviceAccountName: ""
status: {}
