apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-kompose.yml
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: ui
  name: ui
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: ui
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-kompose.yml
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.network/distributed-ga: "true"
        io.kompose.service: ui
    spec:
      containers:
      - env:
        - name: API_URL
          value: http://localhost:9000
        - name: CHANNEL_URL
          value: ws://localhost:9000/subscribe
        - name: NODE_ENV
          value: development
        - name: PORT
          value: "3000"
        image: julesyoungberg/distributed-evolution-ui
        imagePullPolicy: ""
        name: ui
        ports:
        - containerPort: 3000
        resources: {}
        volumeMounts:
        - mountPath: /app
          name: ui-claim0
        - mountPath: /app/node_modules/
          name: ui-claim1
        - mountPath: /app/.next
          name: ui-claim2
      restartPolicy: Always
      serviceAccountName: ""
      volumes:
      - name: ui-claim0
        persistentVolumeClaim:
          claimName: ui-claim0
      - name: ui-claim1
        persistentVolumeClaim:
          claimName: ui-claim1
      - name: ui-claim2
        persistentVolumeClaim:
          claimName: ui-claim2
status: {}
