apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-kompose.yml
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: worker
  name: worker
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: worker
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-kompose.yml
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.network/distributed-ga: "true"
        io.kompose.service: worker
    spec:
      containers:
      - env:
        - name: MASTER_URL
          value: master:8080
        - name: REDIS_MASTER_NAME
          value: mymaster
        - name: SENTINEL_ADDRESS
          value: sentinel:26379
        - name: THREADS
          value: "5"
        image: julesyoungberg/distributed-evolution-worker
        imagePullPolicy: ""
        name: worker
        resources: {}
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status: {}
