apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: worker
  name: worker
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: worker
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.service: worker
    spec:
      containers:
      - name: worker
        image: julesyoungberg/distributed-evolution-worker
        imagePullPolicy: ""
        env:
        - name: GET_HOSTS_FROM
          value: dns
        - name: MASTER_URL
          value: http://master:8080
        - name: REDIS_MASTER_NAME
          value: mymaster
        - name: SENTINELS
          value: redis://sentinel:26379
        - name: THREADS
          value: "5"
        resources: {}
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status: {}
