---
version: '3'

services:
    ui:
        build: .
        environment: 
            API_URL: http://34.107.198.190/api
            CHANNEL_URL: ws://34.107.198.190/api/subscribe
            NODE_ENV: development
            PORT: 3000
        ports:
            - 3000:3000
        restart: unless-stopped
        volumes:
            - ./:/app
            - /app/node_modules/
            - /app/.next
